# Generated by Django 3.1.5 on 2021-03-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='data_type',
            field=models.DateField(blank=True, null=True),
        ),
    ]
