# Generated by Django 3.1.5 on 2021-01-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210106_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
